interface Resources {
  translation: {
    search: string
    hero: {
      title: string
      description: string
    }
    filter: {
      title1: string
      title2: string
      title3: string
      title4: string
      placeholder: string
      search: string
    }
    Navbar: {
      link1: string
      subLink1: string
      link2: string
      link3: string
      link4: string
      link5: string
      link6: string
    }
    PopularCarBodyType: {
      title: string
      link: string
    }
    TopOffers: {
      title: string
      link: string
    }
    LatestCars: {
      title: string
      link: string
    }
    PromeApart: {
      title: string
      link: string
      subTitle1: string
      description1: string
      subTitle2: string
      description2: string
      subTitle3: string
      description3: string
      subTitle4: string
      description4: string
      subTitle5: string
      description5: string
      subTitle6: string
      description6: string
    }
    TopOffersProductCard: {
      gearType: string
      fuelType: string
    }
    CatalogProduct: {
      gearType: string
      fuelType: string
    }
    Sortby: {
      sortbyTitle: string
      compareTitle: string
      item1: string
      item2: string
      item3: string
      item4: string
    }
    Catalog: {
      breadcrumbItem1: string
      locationTitle: string
      priceTitle: string
      priceDescription: string
      yearTitle: string
      modelTitle: string
      bodyTypeTitle: string
      selectedTitle: string
      selectedLink: string
      selectedItem1: string
      selectedItem2: string
      selectedItem3: string
      selectedItem4: string
      selectedItem5: string
      selectedItem6: string
      selectedItem7: string
      drivetrainTitle: string
      drivetrainItem1: string
      drivetrainItem2: string
      drivetrainItem3: string
      fuelTypeTitle: string
      fuelTypeItem1: string
      fuelTypeItem2: string
      fuelTypeItem3: string
      fuelTypeItem4: string
      fuelTypeItem5: string
      fuelTypeItem6: string
      transmissionTitle: string
      transmissionItem1: string
      transmissionItem2: string
      mileageTitle: string
      colorTitle: string
      colorItem1: string
      colorItem2: string
      colorItem3: string
      colorItem4: string
      colorItem5: string
      colorItem6: string
      colorItem7: string
      colorItem8: string
      colorItem9: string
      colorItem10: string
      colorItem11: string
      colorItem12: string
      sellersTitle: string
      sellersItem1: string
      sellersItem2: string
    }
    CatalogTitle: {
      title: string
      offers: string
      subTitle: string
    }
    ProductDetails: {
      productTitle: string
      alt1: string
      published1: string
      published2: string
      published3: string
      miles: string
      newsletterTitle: string
      newsletterSubscribe: string
      newsletterRules: string
      newsletterPlaceholder: string
      privatesellerTitle: string
      privatesellerOtherSeller: string
      privatesellerReveal: string
      privatesellerMessage: string
      privatesellerReviews: string
      privatesellerTitle: string
      privatesellerOtherSeller: string
      privatesellerReveal: string
      privatesellerMessage: string
      privatesellerReviews: string
      specificationsTitle: string
      specificationsText1: string
      specificationsText2: string
      specificationsText3: string
      specificationsText4: string
      specificationsText5: string
      specificationsText6: string
      specificationsText7: string
      specificationsText8: string
      specificationsText9: string
      specificationsText10: string
      specificationsText11: string
      specificationsText12: string
      specificationsValue1: string
      specificationsValue2: string
      specificationsValue3: string
      specificationsValue4: string
      specificationsValue5: string
      specificationsValue6: string
      specificationsValue7: string
      specificationsValue8: string
      specificationsValue9: string
      featuresCardDescription1: string
      featuresCardDescription2: string
      featuresCardDescription3: string
      featuresCardDescription4: string
      featuresTitle1: string
      featuresSubTitle1: string
      featuresSubTitle2: string
      featuresSubTitle3: string
      featuresSubTitle4: string
      featuresItem1: string
      sellerTitle: string
      sellerDescription: string
      sellerMore: string
    }
    LatestCarsProductCard: {
      gearType: string
      fuelType: string
    }
    TopRated: {
      title: string
      description: string
    }
    LatestNews: {
      title: string
      link: string
      tag1: string
      alt1: string
      subTitle1: string
      comment1: string
      comment2: string
      tag2: string
      alt2: string
      subTitle2: string
      comment3: string
      comment4: string
      tag3: string
      alt3: string
      subTitle3: string
      comment5: string
      comment6: string
    }
    NewsCard: {
      comments: string
    }
    About: {
      breadcrumbTitle: string
      searchCarTitle: string
      searchCarDescription: string
      searchCarButton: string
      personalizedTitle: string
      personalizedDescription: string
      personalizedButton: string
      conditionsTitle: string
      conditionsDescription: string
      conditionsButton: string
      growingFastTitle: string
      growingFastSubTitle1: string
      growingFastSubTitle2: string
      growingFastSubTitle3: string
      growingFastDescription1: string
      growingFastDescription2: string
      growingFastDescription3: string
      ourStoryTitle: string
      ourStoryDescription1: string
      ourStoryDescription2: string
      ourStoryDescription3: string
      ourStoryDescription4: string
      faqTitle: string
      faqDescription: string
      faqButton: string
      faqSubTitle1: string
      faqSubTitle2: string
      faqSubTitle3: string
      faqSubTitle4: string
      faqSubTitle5: string
      faqSubTitle6: string
      faqSubTitle7: string
      faqSubDescription1: string
    }
    Contact: {
      contactTitle: string
      contactDescription: string
      contactSubTitle1: string
      contactSubTitle2: string
      contactSubTitle3: string
      contactSubDescription1: string
      contactSubDescription2: string
      contactSubDescription3: string
      contactLink1: string
      contactLink2: string
      contactLink3: string
      contactLabel1: string
      contactLabel2: string
      contactLabel3: string
      contactLabel4: string
      contactItem1: string
      contactItem2: string
      contactItem3: string
      contactItem4: string
      contactPlaceholder1: string
      contactPlaceholder2: string
      contactPlaceholder3: string
      contactButton: string
    }
    typeSwitcher: {
      situation1: string
      situation2: string
      certified1: string
    }
    CarPart: {
      title1: string
      description1: string
      buttonText1: string
      subDescription1: string
      alt1: string
      subDescription2: string
      alt2: string
      subDescription3: string
      alt3: string
      subDescription4: string
      alt4: string
      title2: string
      description2: string
      buttonText2: string
      subDescription5: string
      alt5: string
      subDescription6: string
      alt6: string
      subDescription7: string
      alt7: string
    }
    Footer: {
      locationItem1: string
      placeholder: string
      title1: string
      description1: string
      title2: string
      description2: string
      description3: string
      description4: string
      description5: string
      description6: string
      title3: string
      description7: string
      description8: string
      description9: string
      description10: string
      description11: string
      title4: string
      description12: string
      description13: string
      description14: string
      description15: string
      copyright: string
      terms: string
    }
  }
}

export default Resources
