import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@components/Navbar'
import Footer from '@components/Footer'
import clsx from 'clsx'
import { languages } from '../i18n/settings'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
  children: React.ReactNode
  params: {
    lng: string
  }
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: 'Prome Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps) {
  return (
    <html lang={lng}>
      <body className={clsx(inter.className, 'bg-white dark:bg-main-700')}>
        <Navbar lng={lng} />
        {children}
        <Footer lng={lng} />
      </body>
    </html>
  )
}
